In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train = pd.read_csv('Train.csv')
train.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [3]:
train.shape

(13320, 9)

In [4]:
test = pd.read_csv('Test.csv')
test.head()

area_type   availability           location       size  society  \
0  Super built-up  Area  Ready To Move        Brookefield      2 BHK  Roeekbl   
1            Plot  Area  Ready To Move      Akshaya Nagar  9 Bedroom      NaN   
2            Plot  Area         18-Apr        Hennur Road  4 Bedroom  Saandtt   
3  Super built-up  Area  Ready To Move  Kodichikkanahalli      3 BHK  Winerri   
4  Super built-up  Area  Ready To Move        Konanakunte      2 BHK  AmageSa   

  total_sqft  bath  balcony  price  
0       1225   2.0      2.0    NaN  
1       2400   9.0      2.0    NaN  
2       1650   5.0      2.0    NaN  
3       1322   3.0      1.0    NaN  
4       1161   2.0      1.0    NaN

In [5]:
test.shape

(1480, 9)

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
area_type       13320 non-null object
availability    13320 non-null object
location        13319 non-null object
size            13304 non-null object
society         7818 non-null object
total_sqft      13320 non-null object
bath            13247 non-null float64
balcony         12711 non-null float64
price           13320 non-null float64
dtypes: float64(3), object(6)
memory usage: 936.6+ KB


In [7]:
train['area_type'].value_counts()

Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: area_type, dtype: int64

In [8]:
train['area_type'] = train['area_type'].replace({'Super built-up  Area':0, 'Built-up  Area':1, 'Plot  Area': 2,
                                                'Carpet  Area' :4})
train['area_type'].value_counts()

0    8790
1    2418
2    2025
4      87
Name: area_type, dtype: int64

In [9]:
train['availability'].unique()

array(['19-Dec', 'Ready To Move', '18-May', '18-Feb', '18-Nov', '20-Dec',
       '17-Oct', '21-Dec', '19-Sep', '20-Sep', '18-Mar', '20-Feb',
       '18-Apr', '20-Aug', '18-Oct', '19-Mar', '17-Sep', '18-Dec',
       '17-Aug', '19-Apr', '18-Jun', '22-Dec', '22-Jan', '18-Aug',
       '19-Jan', '17-Jul', '18-Jul', '21-Jun', '20-May', '19-Aug',
       '18-Sep', '17-May', '17-Jun', '21-May', '18-Jan', '20-Mar',
       '17-Dec', '16-Mar', '19-Jun', '22-Jun', '19-Jul', '21-Feb',
       'Immediate Possession', '19-May', '17-Nov', '20-Oct', '20-Jun',
       '19-Feb', '21-Oct', '21-Jan', '17-Mar', '17-Apr', '22-May',
       '19-Oct', '21-Jul', '21-Nov', '21-Mar', '16-Dec', '22-Mar',
       '20-Jan', '21-Sep', '21-Aug', '14-Nov', '19-Nov', '15-Nov',
       '16-Jul', '15-Jun', '17-Feb', '20-Nov', '20-Jul', '16-Sep',
       '15-Oct', '15-Dec', '16-Oct', '22-Nov', '15-Aug', '17-Jan',
       '16-Nov', '20-Apr', '16-Jan', '14-Jul'], dtype=object)

In [10]:
def feature_engineering(availability):
    if availability == 'Ready To Move':
        return 0
    elif availability == 'Immediate Possession':
        return 1
    else:
        return 2

In [11]:
train['availability'] = train['availability'].apply(feature_engineering)

In [12]:
train['availability'].value_counts()

0    10581
2     2723
1       16
Name: availability, dtype: int64

In [13]:
train['location'] = train['location'].fillna('Unknown Location')

In [14]:
train['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [15]:
train['size'] = train['size'].fillna('Others')

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [17]:
train['size'] = le.fit_transform(train['size'])
train['size'].unique()

array([13, 19, 16, 18, 24, 17,  0,  2,  1, 28, 14, 26, 21, 25, 23, 22,  5,
       29, 31, 30, 15,  4,  6,  3, 12, 10, 20,  9, 27,  7,  8, 11],
      dtype=int64)

In [18]:
train['society'] = train['society'].fillna('Others')

In [19]:
train['society'] = le.fit_transform(train['society'])

In [20]:
def fe_total_sqft(total_sqft):
    if len(total_sqft) == 1:
        
        try:
            return float(total_sqft[0])
        except:
            strings = ['Sq. Meter', 'Sq. Yards', 'Perch', 'Acres', 'Cents', 'Guntha', 'Grounds']
            split_total_sqft = re.split('(\d*.*\d)', total_sqft[0])[1:]
            area = float(split_total_sqft[0])
            type_of_area = split_total_sqft[1]
            
            if type_of_area == 'Sq. Meter':
                area_in_sqft = area * 10.7639
            elif type_of_area == 'Sq. Yards':
                area_in_sqft = area * 9.0
            elif type_of_area == 'Perch':
                area_in_sqft = area * 272.25
            elif type_of_area == 'Acres':
                area_in_sqft = area * 43560.0
            elif type_of_area == 'Cents':
                area_in_sqft = area * 435.61545
            elif type_of_area == 'Guntha':
                area_in_sqft = area * 1089.0
            elif type_of_area == 'Grounds':
                area_in_sqft = area * 2400.0
            return float(area_in_sqft)
        
    else:
        return (float(total_sqft[0]) + float(total_sqft[1]))/2.0

In [21]:
train['total_sqft'] = train['total_sqft'].str.split('-').apply(fe_total_sqft)

In [22]:
train['bath'] = train['bath'].groupby(train['location']).transform(lambda x: x.fillna(x.mean()))

In [23]:
train['bath'] = train['bath'].fillna(train['bath'].mean())

In [24]:
train['balcony'] = train['balcony'].groupby(train['location']).transform(lambda x:x.fillna(x.mean()))

In [25]:
train['balcony'] = train['balcony'].fillna(train['balcony'].mean())

In [26]:
train['location'] = le.fit_transform(train['location'])
train['location'].nunique()

1306

In [27]:
train['location'].unique()

array([ 419,  317, 1180, ...,   18,  512,   87], dtype=int64)

In [28]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
area_type       13320 non-null int64
availability    13320 non-null int64
location        13320 non-null int32
size            13320 non-null int32
society         13320 non-null int32
total_sqft      13320 non-null float64
bath            13320 non-null float64
balcony         13320 non-null float64
price           13320 non-null float64
dtypes: float64(4), int32(3), int64(2)
memory usage: 780.5 KB


In [29]:
test = test.drop('price', axis = 1)

In [30]:
test.isnull().sum()

area_type         0
availability      0
location          0
size              2
society         626
total_sqft        0
bath              7
balcony          69
dtype: int64

In [31]:
test['area_type'] = test['area_type'].replace({'Super built-up  Area':0, 'Built-up  Area':1, 'Plot  Area': 2,
                                                'Carpet  Area' :4})
test['area_type'].value_counts()

0    946
1    270
2    254
4     10
Name: area_type, dtype: int64

In [32]:
test['availability'] = test['availability'].apply(feature_engineering)
test['availability'].value_counts()

0    1162
2     316
1       2
Name: availability, dtype: int64

In [33]:
test['location'] = test['location'].fillna('Unknown Location')

In [34]:
test['size'] = test['size'].fillna('Others')

In [35]:
test['size'] = le.fit_transform(test['size'])
test['size'].unique()

array([ 5, 20, 10,  7,  9,  0,  8,  1,  6, 12, 15, 18, 14, 21, 16,  2, 11,
       19, 13, 17,  3,  4], dtype=int64)

In [36]:
test['society'] = test['society'].fillna('Others')
test['society'] = le.fit_transform(test['society'])

In [37]:
test['total_sqft'] = test['total_sqft'].str.split('-').apply(fe_total_sqft)

In [38]:
test['bath'] = test['bath'].groupby(test['location']).transform(lambda x: x.fillna(x.mean()))
test['bath'] = test['bath'].fillna(test['bath'].mean())

In [39]:
test['balcony'] = test['balcony'].groupby(test['location']).transform(lambda x:x.fillna(x.mean()))
test['balcony'] = test['balcony'].fillna(test['balcony'].mean())

In [40]:
test['location'] = le.fit_transform(test['location'])
test['location'].nunique()

495

In [41]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1480 entries, 0 to 1479
Data columns (total 8 columns):
area_type       1480 non-null int64
availability    1480 non-null int64
location        1480 non-null int32
size            1480 non-null int32
society         1480 non-null int32
total_sqft      1480 non-null float64
bath            1480 non-null float64
balcony         1480 non-null float64
dtypes: float64(3), int32(3), int64(2)
memory usage: 75.2 KB


In [42]:
x_train = train.drop('price', axis = 1)
y_train = train['price']
x_test = test

In [53]:
from xgboost import XGBRegressor
xgb = XGBRegressor()
xgb_pred = xgb.fit(x_train, y_train).predict(x_test)

print('Training score is ', xgb.score(x_train, y_train))
solution = pd.DataFrame({'price': xgb_pred})
solution.to_csv('XGB.csv', index = False)

C:\Users\Akshay\Anaconda3\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
C:\Users\Akshay\Anaconda3\lib\site-packages\xgboost\core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \


[15:46:02] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
Training score is  0.7250616611988655
