In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [2]:
train = pd.read_csv('train.csv')
train.head()

ID         author                                             Review  \
0  39467  rayinstirling  Today I'm working on my &quot;Quirky Q&quot; c...   
1  30154    DirtyRose17  @ShannonElizab dont ya know? people love the h...   
2  16767  yoliemichelle  ughhh rejected from the 09 mediation program. ...   
3   9334    jayamelwani     @petewentz im so jealous. i want an octo drive   
4  61178     aliisanoun  I remember all the hype around this movie when...   

   Sentiment  
0          2  
1          1  
2          0  
3          0  
4          0

In [3]:
train.shape

(44100, 4)

In [4]:
train.isnull().sum()

ID           0
author       0
Review       0
Sentiment    0
dtype: int64

In [5]:
train.duplicated().sum()

0

In [6]:
test = pd.read_csv('test.csv')
test.head()

ID          author                                             Review
0  29536    nathantbaker  @amyswarren ahhh yay! I'm getting into it. Kno...
1  13442    Umatter2Chtr  @DeliverImHungry You are right.  If you ordere...
2  54697  bella_cullen_4  I'd heard a lot of bad things about this film ...
3   7007   marviemorales  I miss the old... HA, HA. I can't tell that pe...
4  34410         phaoloo                                 @dharshana anytime

In [7]:
test.shape

(18900, 3)

In [8]:
test.isnull().sum()

ID        0
author    0
Review    0
dtype: int64

In [9]:
train['author'].nunique()

27996

In [10]:
newtrain = train
newtest = test

In [11]:
newtrain = newtrain.drop(['ID', 'author'], axis = 1)
newtest = newtest.drop(['ID', 'author'], axis = 1)

In [12]:
from bs4 import BeautifulSoup

In [13]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [14]:
ps = PorterStemmer()

In [15]:
from nltk.stem import WordNetLemmatizer

lem = WordNetLemmatizer()

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
count_vec = CountVectorizer()

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(newtrain['Review'], newtrain['Sentiment'], test_size = 0.3, random_state = 0)

In [18]:
corpus_train = []
corpus_test  = []

for i in range(x_train.shape[0]):
    soup = BeautifulSoup(x_train.iloc[i], "html.parser")
    review = soup.get_text()
    review = re.sub('\[[^]]*\]', ' ', review)
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    lem = WordNetLemmatizer()
    review = [lem.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus_train.append(review)

In [19]:
for j in range(x_test.shape[0]):
    soup = BeautifulSoup(x_test.iloc[j], "html.parser")
    review = soup.get_text()
    review = re.sub('\[[^]]*\]', ' ', review)
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    lem = WordNetLemmatizer()
    review = [lem.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus_test.append(review)

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vec = TfidfVectorizer(ngram_range=(1, 3))

tfidf_vec_train = tfidf_vec.fit_transform(corpus_train)
tfidf_vec_test = tfidf_vec.transform(corpus_test)

In [21]:
from sklearn.svm import LinearSVC
linear_svc = LinearSVC(C=0.5, random_state=42)

In [22]:
linear_svc.fit(tfidf_vec_train, y_train)

LinearSVC(C=0.5, random_state=42)

In [23]:
predict = linear_svc.predict(tfidf_vec_test)

In [24]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [25]:
print(classification_report(y_test, predict))

              precision    recall  f1-score   support

           0       0.69      0.77      0.72      5699
           1       0.43      0.10      0.16      1856
           2       0.69      0.78      0.73      5675

    accuracy                           0.68     13230
   macro avg       0.60      0.55      0.54     13230
weighted avg       0.65      0.68      0.65     13230



In [26]:
print(confusion_matrix(y_test, predict))

[[4367  114 1218]
 [ 866  183  807]
 [1122  127 4426]]


In [27]:
print("Accuracy:", accuracy_score(y_test, predict))

Accuracy: 0.6784580498866213


In [28]:
x_train = newtrain['Review']
y_train = newtrain['Sentiment']
x_test = newtest['Review']

In [29]:
corpus_train = []
corpus_test  = []

for i in range(x_train.shape[0]):
    soup = BeautifulSoup(x_train.iloc[i], "html.parser")
    review = soup.get_text()
    review = re.sub('\[[^]]*\]', ' ', review)
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    lem = WordNetLemmatizer()
    review = [lem.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus_train.append(review)

In [30]:
for j in range(x_test.shape[0]):
    soup = BeautifulSoup(x_test.iloc[j], "html.parser")
    review = soup.get_text()
    review = re.sub('\[[^]]*\]', ' ', review)
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    lem = WordNetLemmatizer()
    review = [lem.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus_test.append(review)

C:\Users\Akshay.Patil\Anaconda3\lib\site-packages\bs4\__init__.py:332: MarkupResemblesLocatorWarning: "Con: spotty service." looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(


In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vec = TfidfVectorizer(ngram_range=(1, 3))

tfidf_vec_train = tfidf_vec.fit_transform(corpus_train)
tfidf_vec_test = tfidf_vec.transform(corpus_test)

In [32]:
from sklearn.svm import LinearSVC
linear_svc = LinearSVC(C=0.5, random_state=42)

In [33]:
linear_svc.fit(tfidf_vec_train, y_train)

LinearSVC(C=0.5, random_state=42)

In [34]:
y_pred = linear_svc.predict(tfidf_vec_test)

In [35]:
solution = pd.DataFrame({'Sentiment': y_pred})

In [36]:
from sklearn.preprocessing import OneHotEncoder
oe = OneHotEncoder()
db = pd.get_dummies(solution['Sentiment'])

In [37]:
db = db.rename({0: 'Negative_0', 1 : 'Neutral_1', 2 : 'Positive_2'}, axis = 1)
db

Negative_0  Neutral_1  Positive_2
0               0          0           1
1               1          0           0
2               1          0           0
3               0          0           1
4               0          0           1
...           ...        ...         ...
18895           1          0           0
18896           0          0           1
18897           1          0           0
18898           1          0           0
18899           1          0           0

[18900 rows x 3 columns]

In [38]:
db.to_csv('Solution.csv', index = False)