In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train = pd.read_excel('Data_Train.xlsx')
train.head()

STORY  SECTION
0  But the most painful was the huge reversal in ...        3
1  How formidable is the opposition alliance amon...        0
2  Most Asian currencies were trading lower today...        3
3  If you want to answer any question, click on ‘...        1
4  In global markets, gold prices edged up today ...        3

In [3]:
train.shape

(7628, 2)

In [4]:
test = pd.read_excel('Data_Test.xlsx')
test.head()

STORY
0  2019 will see gadgets like gaming smartphones ...
1  It has also unleashed a wave of changes in the...
2  It can be confusing to pick the right smartpho...
3  The mobile application is integrated with a da...
4  We have rounded up some of the gadgets that sh...

In [5]:
test.shape

(2748, 1)

In [6]:
train.isnull().sum()

STORY      0
SECTION    0
dtype: int64

In [7]:
test.isnull().sum()

STORY    0
dtype: int64

In [8]:
from bs4 import BeautifulSoup

In [9]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [10]:
ps = PorterStemmer()

In [11]:
from nltk.stem import WordNetLemmatizer

lem = WordNetLemmatizer()

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
count_vec = CountVectorizer()

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train['STORY'], train['SECTION'], test_size = 0.3, random_state = 0)

In [14]:
corpus_train = []
corpus_test  = []

for i in range(x_train.shape[0]):
    soup = BeautifulSoup(x_train.iloc[i], "html.parser")
    review = soup.get_text()
    review = re.sub('\[[^]]*\]', ' ', review)
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    lem = WordNetLemmatizer()
    review = [lem.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus_train.append(review)

In [15]:
for j in range(x_test.shape[0]):
    soup = BeautifulSoup(x_test.iloc[j], "html.parser")
    review = soup.get_text()
    review = re.sub('\[[^]]*\]', ' ', review)
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    lem = WordNetLemmatizer()
    review = [lem.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus_test.append(review)

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vec = TfidfVectorizer(ngram_range=(1, 3))

tfidf_vec_train = tfidf_vec.fit_transform(corpus_train)
tfidf_vec_test = tfidf_vec.transform(corpus_test)

In [17]:
from sklearn.svm import LinearSVC
linear_svc = LinearSVC(C=0.5, random_state=42)

In [18]:
linear_svc.fit(tfidf_vec_train, y_train)

LinearSVC(C=0.5, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=42, tol=0.0001,
          verbose=0)

In [19]:
predict = linear_svc.predict(tfidf_vec_test)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [21]:
print(classification_report(y_test, predict))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       527
           1       0.96      0.99      0.97       810
           2       0.99      0.96      0.98       571
           3       0.98      0.97      0.98       381

    accuracy                           0.97      2289
   macro avg       0.97      0.97      0.97      2289
weighted avg       0.97      0.97      0.97      2289



In [22]:
print(confusion_matrix(y_test, predict))

[[506  17   2   2]
 [  4 801   2   3]
 [ 16   6 548   1]
 [  1  10   0 370]]


In [23]:
print("Accuracy:", accuracy_score(y_test, predict))

Accuracy: 0.9720401922236784


In [25]:
x_train = train['STORY']
y_train = train['SECTION']
x_test = test['STORY']

In [26]:
corpus_train = []
corpus_test  = []

for i in range(x_train.shape[0]):
    soup = BeautifulSoup(x_train.iloc[i], "html.parser")
    review = soup.get_text()
    review = re.sub('\[[^]]*\]', ' ', review)
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    lem = WordNetLemmatizer()
    review = [lem.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus_train.append(review)

In [27]:
for j in range(x_test.shape[0]):
    soup = BeautifulSoup(x_test.iloc[j], "html.parser")
    review = soup.get_text()
    review = re.sub('\[[^]]*\]', ' ', review)
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    lem = WordNetLemmatizer()
    review = [lem.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus_test.append(review)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vec = TfidfVectorizer(ngram_range=(1, 3))

tfidf_vec_train = tfidf_vec.fit_transform(corpus_train)
tfidf_vec_test = tfidf_vec.transform(corpus_test)

In [29]:
from sklearn.svm import LinearSVC
linear_svc = LinearSVC(C=0.5, random_state=42)

In [30]:
linear_svc.fit(tfidf_vec_train, y_train)

LinearSVC(C=0.5, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=42, tol=0.0001,
          verbose=0)

In [31]:
y_pred = linear_svc.predict(tfidf_vec_test)

In [33]:
solution = pd.DataFrame({'SECTION': y_pred})
solution.to_excel('Solution1.xlsx', index = False)